# Generated by Django 5.2.17 on 2026-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='is_available',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('not_available', 'Not Available')], default='available', max_length=20),
        ),
    ]
