# Generated by Django 5.2.17 on 2026-10-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_remove_donorprofile_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='blood/supporting_documents/'),
        ),
    ]
