# Generated by Django 5.2.17 on 2026-09-22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("score", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rated_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ratings_received", to=settings.AUTH_USER_MODEL)),
                ("rater", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ratings_given", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [models.UniqueConstraint(fields=("rater", "rated_user"), name="unique_rating_per_rater_and_user")],
            },
        ),
    ]
