# Generated by Django 5.2.17 on 2026-09-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='rating',
        ),
    ]
