# Generated by Django 5.2.17 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0002_alter_user_managers")]

    operations = [
        migrations.AddField(model_name="user", name="bio", field=models.TextField(blank=True)),
        migrations.AddField(model_name="user", name="date_of_birth", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="user", name="gender", field=models.CharField(blank=True, choices=[("female", "Female"), ("male", "Male"), ("other", "Other"), ("not_specified", "Prefer not to say")], max_length=20)),
        migrations.AddField(model_name="user", name="is_date_of_birth_visible", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="user", name="is_email_visible", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="user", name="is_location_visible", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="user", name="is_phone_visible", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="user", name="profile_picture", field=models.ImageField(blank=True, null=True, upload_to="profile_pictures/")),
    ]
