# Generated by Django 5.2.17 on 2026-09-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('NGO', 'NGO'), ('Volunteer', 'Volunteer'), ('Farmer', 'Farmer'), ('Blood Donor', 'Blood Donor'), ('Admin', 'Admin')], default='Citizen', max_length=20),
        ),
    ]
