# Generated by Django 5.2.17 on 2026-09-28 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WastePickupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waste_type', models.CharField(choices=[('Organic', 'Organic / Kitchen Waste'), ('Recyclable', 'Recyclable / Plastic & Paper'), ('Electronic', 'Electronic / E-Waste'), ('Hazardous', 'Hazardous / Medical Waste'), ('Bulk', 'Bulk / Construction Waste'), ('General', 'General / Other Waste')], default='General', max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('preferred_pickup_date', models.DateField(blank=True, null=True)),
                ('preferred_pickup_time', models.CharField(blank=True, max_length=50)),
                ('preferred_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Contacted', 'Contacted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_waste_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
